"""timestamp

Revision ID: 82e3376a8706
Revises: c37d64328354
Create Date: 2025-07-27 09:29:42.830445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e3376a8706'
down_revision: Union[str, Sequence[str], None] = 'c37d64328354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil_aridity', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('soil_moisture', sa.Column('timestamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soil_moisture', 'timestamp')
    op.drop_column('soil_aridity', 'timestamp')
    # ### end Alembic commands ###
